name: Lab 1 - MapReduce

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Lab 1 - MapReduce
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test lab1
      run: |
        go env -w GO111MODULE="off"
        cd src/main
        sh test-mr.sh
